language: java
jdk:
  - oraclejdk8   

before_install:
  - chmod +x gradlew  
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs
  - git lfs install
  - git lfs pull
 